# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'block_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BlockDialog(object):
    def setupUi(self, BlockDialog):
        BlockDialog.setObjectName("BlockDialog")
        BlockDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(BlockDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleEdit = QtWidgets.QLineEdit(BlockDialog)
        self.titleEdit.setObjectName("titleEdit")
        self.titleEdit.setPlaceholderText("Title")
        self.verticalLayout.addWidget(self.titleEdit)
        self.startTimeEdit = QtWidgets.QTimeEdit(BlockDialog)
        self.startTimeEdit.setObjectName("startTimeEdit")
        self.verticalLayout.addWidget(self.startTimeEdit)
        self.endTimeEdit = QtWidgets.QTimeEdit(BlockDialog)
        self.endTimeEdit.setObjectName("endTimeEdit")
        self.verticalLayout.addWidget(self.endTimeEdit)
        self.colorButton = QtWidgets.QPushButton(BlockDialog)
        self.colorButton.setObjectName("colorButton")
        self.verticalLayout.addWidget(self.colorButton)
        self.descriptionEdit = QtWidgets.QTextEdit(BlockDialog)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.descriptionEdit.setPlaceholderText("Description")
        self.verticalLayout.addWidget(self.descriptionEdit)
        self.saveButton = QtWidgets.QPushButton(BlockDialog)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(BlockDialog)
        QtCore.QMetaObject.connectSlotsByName(BlockDialog)

    def retranslateUi(self, BlockDialog):
        _translate = QtCore.QCoreApplication.translate
        BlockDialog.setWindowTitle(_translate("BlockDialog", "Add/Edit Block"))
        self.colorButton.setText(_translate("BlockDialog", "Select Color"))
        self.saveButton.setText(_translate("BlockDialog", "Save"))
