# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.blockListView = QtWidgets.QListView(self.centralwidget)
        self.blockListView.setObjectName("blockListView")
        self.verticalLayout.addWidget(self.blockListView)
        self.searchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.searchBar.setObjectName("searchBar")
        self.searchBar.setPlaceholderText("Search...")
        self.verticalLayout.addWidget(self.searchBar)
        self.buttonWidget = QtWidgets.QWidget(self.centralwidget)
        self.buttonWidget.setObjectName("buttonWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBlockButton = QtWidgets.QPushButton(self.buttonWidget)
        self.addBlockButton.setObjectName("addBlockButton")
        self.horizontalLayout.addWidget(self.addBlockButton)
        self.editBlockButton = QtWidgets.QPushButton(self.buttonWidget)
        self.editBlockButton.setObjectName("editBlockButton")
        self.horizontalLayout.addWidget(self.editBlockButton)
        self.deleteBlockButton = QtWidgets.QPushButton(self.buttonWidget)
        self.deleteBlockButton.setObjectName("deleteBlockButton")
        self.horizontalLayout.addWidget(self.deleteBlockButton)
        self.completeBlockButton = QtWidgets.QPushButton(self.buttonWidget)
        self.completeBlockButton.setObjectName("completeBlockButton")
        self.horizontalLayout.addWidget(self.completeBlockButton)
        self.themeButton = QtWidgets.QPushButton(self.buttonWidget)
        self.themeButton.setObjectName("themeButton")
        self.horizontalLayout.addWidget(self.themeButton)
        self.verticalLayout.addWidget(self.buttonWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Timetune"))
        self.addBlockButton.setText(_translate("MainWindow", "Add Block"))
        self.editBlockButton.setText(_translate("MainWindow", "Edit Block"))
        self.deleteBlockButton.setText(_translate("MainWindow", "Delete Block"))
        self.completeBlockButton.setText(_translate("MainWindow", "Complete Block"))
        self.themeButton.setText(_translate("MainWindow", "Switch Theme"))
